### ISSUE TITLE
Research missing images

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/beit-hatfutsot-devops#8]
[Interim report 2.xlsx](https://github.com/Beit-Hatfutsot/beit-hatfutsot-devops/files/854318/Interim.report.2.xlsx)

The middle tab of the attached document contains URLs that produce images that return 404.
We need to figure out why this happens.

**Comment by OriHoch** [comment]
Seems like it happened because migration process failed at one point. 

Because currently migration process is monolithic and fragile it's hard to know exactly why

I fixed manually the following image - 
http://dbs.bh.org.il/image/leo-and-dora-hamerman-upstate-new-york-usa-1940s

by running the following on bhs-infra:

```
cd api
. env/bin/activate
export PYTHONPATH=.
python scripts/migrate.py -c photoUnits -i 161888 -s 0
```

and it works now.. need to do the same for other missing images

I'll open a new issue for writing a tool to perform this update

**Comment by OriHoch** [comment]
issue to write a script that will allow to update all images:
https://github.com/Beit-Hatfutsot/dbs-back/issues/127

**Comment by TheGrandVizier** [comment]
Seems investigation is concluded and fixage is on the way. Closing this now.
